import { MenuItem } from '@/types/menu';

const STORAGE_KEY = 'bar_menu_items';

export const getMenuItems = (): MenuItem[] => {
  try {
    const items = localStorage.getItem(STORAGE_KEY);
    return items ? JSON.parse(items) : getSampleData();
  } catch (error) {
    console.error('Error loading menu items:', error);
    return getSampleData();
  }
};

export const saveMenuItems = (items: MenuItem[]): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
  } catch (error) {
    console.error('Error saving menu items:', error);
  }
};

const getSampleData = (): MenuItem[] => [
  {
    id: '1',
    name: 'BOMBIL KOLIWADA',
    category: 'food',
    price: 300,
    available: true,
  },
  {
    id: '2',
    name: 'CHEESE BALLS',
    category: 'food',
    price: 200,
    available: true,
  },
  {
    id: '3',
    name: 'CHEESE GARLIC BREAD',
    category: 'food',
    price: 150,
    available: true,
  },
  // Traditional Indian Drinks
  {
    id: '4',
    name: 'Sweet Lassi',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '5',
    name: 'Salted Lassi',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '6',
    name: 'Mango Lassi',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '7',
    name: 'Chaas / Buttermilk',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '8',
    name: 'Nimbu Pani',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '9',
    name: 'Jaljeera',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '10',
    name: 'Aam Panna',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '11',
    name: 'Thandai',
    category: 'drinks',
    price: 90,
    available: true,
  },
  {
    id: '12',
    name: 'Masala Chai',
    category: 'drinks',
    price: 40,
    available: true,
  },
  {
    id: '13',
    name: 'Cutting Chai',
    category: 'drinks',
    price: 20,
    available: true,
  },
  {
    id: '14',
    name: 'Filter Coffee',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '15',
    name: 'Sugarcane Juice',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '16',
    name: 'Coconut Water',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '17',
    name: 'Rose Milk',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '18',
    name: 'Badam Milk',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '19',
    name: 'Shikanji',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '20',
    name: 'Sol Kadhi',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '21',
    name: 'Paneer Soda',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '22',
    name: 'Jal Jeera Soda',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '23',
    name: 'Kokum Sherbet',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '24',
    name: 'Sattu Drink',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '25',
    name: 'Bel Ka Sharbat',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '26',
    name: 'Kesar Milk',
    category: 'drinks',
    price: 90,
    available: true,
  },
  {
    id: '27',
    name: 'Masala Milk',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '28',
    name: 'Falooda',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '29',
    name: 'Kulfi Shake',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '30',
    name: 'Gulab Sherbet',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '31',
    name: 'Khus Sherbet',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '32',
    name: 'Rooh Afza',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '33',
    name: 'Neer Mor',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '34',
    name: 'Panakam',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '35',
    name: 'Variyali Sherbet',
    category: 'drinks',
    price: 70,
    available: true,
  },
  // Indian Alcoholic Beverages
  {
    id: '36',
    name: 'Cashew Feni',
    category: 'drinks',
    price: 150,
    available: true,
  },
  {
    id: '37',
    name: 'Coconut Feni',
    category: 'drinks',
    price: 140,
    available: true,
  },
  {
    id: '38',
    name: 'Toddy (Palm Wine)',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '39',
    name: 'Mahua',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '40',
    name: 'Arrack',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '41',
    name: 'Indian Whisky (30ml)',
    category: 'drinks',
    price: 150,
    available: true,
  },
  {
    id: '42',
    name: 'Indian Whisky (60ml)',
    category: 'drinks',
    price: 280,
    available: true,
  },
  {
    id: '43',
    name: 'Indian Rum (30ml)',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '44',
    name: 'Indian Rum (60ml)',
    category: 'drinks',
    price: 220,
    available: true,
  },
  {
    id: '45',
    name: 'Indian Gin (30ml)',
    category: 'drinks',
    price: 180,
    available: true,
  },
  {
    id: '46',
    name: 'Indian Gin (60ml)',
    category: 'drinks',
    price: 320,
    available: true,
  },
  {
    id: '47',
    name: 'Indian Vodka (30ml)',
    category: 'drinks',
    price: 130,
    available: true,
  },
  {
    id: '48',
    name: 'Indian Vodka (60ml)',
    category: 'drinks',
    price: 240,
    available: true,
  },
  {
    id: '49',
    name: 'Kingfisher Beer',
    category: 'drinks',
    price: 150,
    available: true,
  },
  {
    id: '50',
    name: 'Kingfisher Strong',
    category: 'drinks',
    price: 170,
    available: true,
  },
  {
    id: '51',
    name: 'Kingfisher Ultra',
    category: 'drinks',
    price: 180,
    available: true,
  },
  {
    id: '52',
    name: 'Bira White',
    category: 'drinks',
    price: 200,
    available: true,
  },
  {
    id: '53',
    name: 'Bira Blonde',
    category: 'drinks',
    price: 200,
    available: true,
  },
  {
    id: '54',
    name: 'Bira Strong',
    category: 'drinks',
    price: 220,
    available: true,
  },
  {
    id: '55',
    name: 'Godfather Beer',
    category: 'drinks',
    price: 180,
    available: true,
  },
  {
    id: '56',
    name: 'Simba Beer',
    category: 'drinks',
    price: 160,
    available: true,
  },
  {
    id: '57',
    name: 'Budweiser',
    category: 'drinks',
    price: 190,
    available: true,
  },
  {
    id: '58',
    name: 'Corona',
    category: 'drinks',
    price: 250,
    available: true,
  },
  {
    id: '59',
    name: 'Hoegaarden',
    category: 'drinks',
    price: 280,
    available: true,
  },
  {
    id: '60',
    name: 'Old Monk Rum',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '61',
    name: 'Officers Choice Whisky',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '62',
    name: 'Royal Challenge Whisky',
    category: 'drinks',
    price: 140,
    available: true,
  },
  {
    id: '63',
    name: 'Amrut Single Malt',
    category: 'drinks',
    price: 350,
    available: true,
  },
  {
    id: '64',
    name: 'Paul John Single Malt',
    category: 'drinks',
    price: 380,
    available: true,
  },
  {
    id: '65',
    name: 'Greater Than Gin',
    category: 'drinks',
    price: 200,
    available: true,
  },
  {
    id: '66',
    name: 'Jaisalmer Indian Craft Gin',
    category: 'drinks',
    price: 220,
    available: true,
  },
  {
    id: '67',
    name: 'Stranger & Sons Gin',
    category: 'drinks',
    price: 240,
    available: true,
  },
  {
    id: '68',
    name: 'Bombay Sapphire',
    category: 'drinks',
    price: 200,
    available: true,
  },
  {
    id: '69',
    name: 'Sula Red Wine',
    category: 'drinks',
    price: 300,
    available: true,
  },
  {
    id: '70',
    name: 'Sula White Wine',
    category: 'drinks',
    price: 300,
    available: true,
  },
  {
    id: '71',
    name: 'Sula Rose Wine',
    category: 'drinks',
    price: 320,
    available: true,
  },
  {
    id: '72',
    name: 'Grover Zampa Wine',
    category: 'drinks',
    price: 350,
    available: true,
  },
  {
    id: '73',
    name: 'Fratelli Wine',
    category: 'drinks',
    price: 380,
    available: true,
  },
  {
    id: '74',
    name: 'Four Seasons Wine',
    category: 'drinks',
    price: 280,
    available: true,
  },
  {
    id: '75',
    name: 'Indian Gin & Tonic',
    category: 'drinks',
    price: 250,
    available: true,
  },
  {
    id: '76',
    name: 'Feni Cocktail',
    category: 'drinks',
    price: 220,
    available: true,
  },
  {
    id: '77',
    name: 'Masala Bloody Mary',
    category: 'drinks',
    price: 280,
    available: true,
  },
  {
    id: '78',
    name: 'Mumbai Mule',
    category: 'drinks',
    price: 260,
    available: true,
  },
  {
    id: '79',
    name: 'Kokum Martini',
    category: 'drinks',
    price: 300,
    available: true,
  },
  {
    id: '80',
    name: 'Aam Panna Vodka',
    category: 'drinks',
    price: 240,
    available: true,
  },
];
