import { MenuItem } from '@/types/menu';

const STORAGE_KEY = 'bar_menu_items';

export const getMenuItems = (): MenuItem[] => {
  try {
    const items = localStorage.getItem(STORAGE_KEY);
    return items ? JSON.parse(items) : getSampleData();
  } catch (error) {
    console.error('Error loading menu items:', error);
    return getSampleData();
  }
};

export const saveMenuItems = (items: MenuItem[]): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
  } catch (error) {
    console.error('Error saving menu items:', error);
  }
};

export const resetMenuItems = (): void => {
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch (error) {
    console.error('Error resetting menu items:', error);
  }
};

const getSampleData = (): MenuItem[] => [
  {
    id: '1',
    name: 'BOMBIL KOLIWADA',
    category: 'food',
    price: 300,
    available: true,
  },
  {
    id: '2',
    name: 'CHEESE BALLS',
    category: 'food',
    price: 200,
    available: true,
  },
  {
    id: '3',
    name: 'CHEESE GARLIC BREAD',
    category: 'food',
    price: 150,
    available: true,
  },
  // Traditional Indian Drinks
  {
    id: '4',
    name: 'Sweet Lassi',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '5',
    name: 'Salted Lassi',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '6',
    name: 'Mango Lassi',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '7',
    name: 'Chaas / Buttermilk',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '8',
    name: 'Nimbu Pani',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '9',
    name: 'Jaljeera',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '10',
    name: 'Aam Panna',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '11',
    name: 'Thandai',
    category: 'drinks',
    price: 90,
    available: true,
  },
  {
    id: '12',
    name: 'Masala Chai',
    category: 'drinks',
    price: 40,
    available: true,
  },
  {
    id: '13',
    name: 'Cutting Chai',
    category: 'drinks',
    price: 20,
    available: true,
  },
  {
    id: '14',
    name: 'Filter Coffee',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '15',
    name: 'Sugarcane Juice',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '16',
    name: 'Coconut Water',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '17',
    name: 'Rose Milk',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '18',
    name: 'Badam Milk',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '19',
    name: 'Shikanji',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '20',
    name: 'Sol Kadhi',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '21',
    name: 'Paneer Soda',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '22',
    name: 'Jal Jeera Soda',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '23',
    name: 'Kokum Sherbet',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '24',
    name: 'Sattu Drink',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '25',
    name: 'Bel Ka Sharbat',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '26',
    name: 'Kesar Milk',
    category: 'drinks',
    price: 90,
    available: true,
  },
  {
    id: '27',
    name: 'Masala Milk',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '28',
    name: 'Falooda',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '29',
    name: 'Kulfi Shake',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '30',
    name: 'Gulab Sherbet',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '31',
    name: 'Khus Sherbet',
    category: 'drinks',
    price: 70,
    available: true,
  },
  {
    id: '32',
    name: 'Rooh Afza',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '33',
    name: 'Neer Mor',
    category: 'drinks',
    price: 60,
    available: true,
  },
  {
    id: '34',
    name: 'Panakam',
    category: 'drinks',
    price: 50,
    available: true,
  },
  {
    id: '35',
    name: 'Variyali Sherbet',
    category: 'drinks',
    price: 70,
    available: true,
  },
  // Indian Alcoholic Beverages
  {
    id: '36',
    name: 'Cashew Feni',
    category: 'drinks',
    price: 150,
    available: true,
  },
  {
    id: '37',
    name: 'Coconut Feni',
    category: 'drinks',
    price: 140,
    available: true,
  },
  {
    id: '38',
    name: 'Toddy (Palm Wine)',
    category: 'drinks',
    price: 80,
    available: true,
  },
  {
    id: '39',
    name: 'Mahua',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '40',
    name: 'Arrack',
    category: 'drinks',
    price: 100,
    available: true,
  },
  {
    id: '41',
    name: 'Indian Whisky (30ml)',
    category: 'drinks',
    price: 150,
    available: true,
  },
  {
    id: '42',
    name: 'Indian Whisky (60ml)',
    category: 'drinks',
    price: 280,
    available: true,
  },
  {
    id: '43',
    name: 'Indian Rum (30ml)',
    category: 'drinks',
    price: 120,
    available: true,
  },
  {
    id: '44',
    name: 'Indian Rum (60ml)',
    category: 'drinks',
    price: 220,
    available: true,
  },
  {
    id: '45',
    name: 'Indian Gin (30ml)',
    category: 'drinks',
    price: 180,
    available: true,
  },
  {
    id: '46',
    name: 'Indian Gin (60ml)',
    category: 'drinks',
    price: 320,
    available: true,
  },
  {
    id: '47',
    name: 'Indian Vodka (30ml)',
    category: 'drinks',
    price: 130,
    available: true,
  },
  {
    id: '48',
    name: 'Indian Vodka (60ml)',
    category: 'drinks',
    price: 240,
    available: true,
  },
  {
    id: '49',
    name: 'Kingfisher Beer',
    category: 'drinks',
    subcategory: 'beer',
    price: 150,
    available: true,
  },
  {
    id: '50',
    name: 'Kingfisher Strong',
    category: 'drinks',
    subcategory: 'beer',
    price: 170,
    available: true,
  },
  {
    id: '51',
    name: 'Kingfisher Ultra',
    category: 'drinks',
    subcategory: 'beer',
    price: 180,
    available: true,
  },
  {
    id: '52',
    name: 'Bira White',
    category: 'drinks',
    subcategory: 'beer',
    price: 200,
    available: true,
  },
  {
    id: '53',
    name: 'Bira Blonde',
    category: 'drinks',
    subcategory: 'beer',
    price: 200,
    available: true,
  },
  {
    id: '54',
    name: 'Bira Strong',
    category: 'drinks',
    subcategory: 'beer',
    price: 220,
    available: true,
  },
  {
    id: '55',
    name: 'Godfather Beer',
    category: 'drinks',
    subcategory: 'beer',
    price: 180,
    available: true,
  },
  {
    id: '56',
    name: 'Simba Beer',
    category: 'drinks',
    subcategory: 'beer',
    price: 160,
    available: true,
  },
  {
    id: '57',
    name: 'Budweiser',
    category: 'drinks',
    subcategory: 'beer',
    price: 190,
    available: true,
  },
  {
    id: '58',
    name: 'Corona',
    category: 'drinks',
    subcategory: 'beer',
    price: 250,
    available: true,
  },
  {
    id: '59',
    name: 'Hoegaarden',
    category: 'drinks',
    subcategory: 'beer',
    price: 280,
    available: true,
  },
  {
    id: '60',
    name: 'Old Monk Rum',
    category: 'drinks',
    subcategory: 'rum',
    price: 100,
    sizes: { '30ml': 45, '60ml': 85, '90ml': 140, '180ml': 215 },
    available: true,
  },
  {
    id: '61',
    name: 'Officers Choice Whisky',
    category: 'drinks',
    subcategory: 'whisky',
    price: 120,
    sizes: { '30ml': 50, '60ml': 90, '90ml': 135, '180ml': 220 },
    available: true,
  },
  {
    id: '62',
    name: 'Royal Challenge Whisky',
    category: 'drinks',
    subcategory: 'whisky',
    price: 140,
    sizes: { '30ml': 60, '60ml': 100, '90ml': 150, '180ml': 240 },
    available: true,
  },
  {
    id: '63',
    name: 'Amrut Single Malt',
    category: 'drinks',
    subcategory: 'whisky',
    price: 350,
    sizes: { '30ml': 250, '60ml': 450, '90ml': 650, '180ml': 1200 },
    available: true,
  },
  {
    id: '64',
    name: 'Paul John Single Malt',
    category: 'drinks',
    price: 380,
    available: true,
  },
  {
    id: '65',
    name: 'Greater Than Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 200,
    sizes: { '30ml': 90, '60ml': 160, '90ml': 230, '180ml': 450 },
    available: true,
  },
  {
    id: '66',
    name: 'Jaisalmer Indian Craft Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 220,
    available: true,
  },
  {
    id: '67',
    name: 'Stranger & Sons Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 240,
    available: true,
  },
  {
    id: '68',
    name: 'Bombay Sapphire',
    category: 'drinks',
    subcategory: 'gin',
    price: 200,
    sizes: { '30ml': 120, '60ml': 220, '90ml': 320, '180ml': 600 },
    available: true,
  },
  {
    id: '69',
    name: 'Sula Red Wine',
    category: 'drinks',
    subcategory: 'wine',
    price: 300,
    available: true,
  },
  {
    id: '70',
    name: 'Sula White Wine',
    category: 'drinks',
    subcategory: 'wine',
    price: 300,
    available: true,
  },
  {
    id: '71',
    name: 'Sula Rose Wine',
    category: 'drinks',
    subcategory: 'wine',
    price: 320,
    available: true,
  },
  {
    id: '72',
    name: 'Grover Zampa Wine',
    category: 'drinks',
    subcategory: 'wine',
    price: 350,
    available: true,
  },
  {
    id: '73',
    name: 'Fratelli Wine',
    category: 'drinks',
    subcategory: 'wine',
    price: 380,
    available: true,
  },
  {
    id: '74',
    name: 'Four Seasons Wine',
    category: 'drinks',
    subcategory: 'wine',
    price: 280,
    available: true,
  },
  {
    id: '75',
    name: 'Indian Gin & Tonic',
    category: 'drinks',
    price: 250,
    available: true,
  },
  {
    id: '76',
    name: 'Feni Cocktail',
    category: 'drinks',
    price: 220,
    available: true,
  },
  {
    id: '77',
    name: 'Masala Bloody Mary',
    category: 'drinks',
    price: 280,
    available: true,
  },
  {
    id: '78',
    name: 'Mumbai Mule',
    category: 'drinks',
    price: 260,
    available: true,
  },
  {
    id: '79',
    name: 'Kokum Martini',
    category: 'drinks',
    price: 300,
    available: true,
  },
  {
    id: '80',
    name: 'Aam Panna Vodka',
    category: 'drinks',
    price: 240,
    available: true,
  },
  // --- POsh Hinjewadi Pune: Comprehensive Alcohol List ---
  // IMFL (Indian Made Foreign Liquor)
  {
    id: '81',
    name: 'Imperial Blue Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 120,
    sizes: { '30ml': 50, '60ml': 90, '90ml': 135, '180ml': 220 },
    available: true,
  },
  {
    id: '82',
    name: 'Royal Stag Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 140,
    sizes: { '30ml': 60, '60ml': 100, '90ml': 150, '180ml': 240 },
    available: true,
  },
  {
    id: '83',
    name: "Blenders Pride Whisky",
    category: 'drinks',
    subcategory: 'imfl',
    price: 180,
    sizes: { '30ml': 80, '60ml': 150, '90ml': 220, '180ml': 400 },
    available: true,
  },
  {
    id: '84',
    name: '8 PM Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 130,
    sizes: { '30ml': 55, '60ml': 95, '90ml': 140, '180ml': 230 },
    available: true,
  },
  {
    id: '85',
    name: 'Bagpiper Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 120,
    sizes: { '30ml': 50, '60ml': 90, '90ml': 135, '180ml': 220 },
    available: true,
  },
  {
    id: '86',
    name: "McDowell's No.1 Rum",
    category: 'drinks',
    subcategory: 'imfl',
    price: 130,
    sizes: { '30ml': 55, '60ml': 100, '90ml': 150, '180ml': 240 },
    available: true,
  },
  {
    id: '87',
    name: 'Old Port Rum',
    category: 'drinks',
    subcategory: 'imfl',
    price: 120,
    sizes: { '30ml': 50, '60ml': 90, '90ml': 140, '180ml': 230 },
    available: true,
  },
  {
    id: '88',
    name: 'Magic Moments Vodka',
    category: 'drinks',
    subcategory: 'imfl',
    price: 160,
    sizes: { '30ml': 70, '60ml': 130, '90ml': 190, '180ml': 360 },
    available: true,
  },
  {
    id: '89',
    name: 'Mansion House Brandy',
    category: 'drinks',
    subcategory: 'imfl',
    price: 150,
    sizes: { '30ml': 65, '60ml': 120, '90ml': 180, '180ml': 340 },
    available: true,
  },
  {
    id: '90',
    name: 'Honey Bee Brandy',
    category: 'drinks',
    subcategory: 'imfl',
    price: 140,
    sizes: { '30ml': 60, '60ml': 110, '90ml': 170, '180ml': 320 },
    available: true,
  },
  // Whisky (Premium & Imported)
  {
    id: '91',
    name: '100 Pipers 12YO',
    category: 'drinks',
    subcategory: 'whisky',
    price: 300,
    sizes: { '30ml': 180, '60ml': 340, '90ml': 500, '180ml': 950 },
    available: true,
  },
  {
    id: '92',
    name: 'Black Dog Triple Gold',
    category: 'drinks',
    subcategory: 'whisky',
    price: 320,
    sizes: { '30ml': 190, '60ml': 360, '90ml': 530, '180ml': 1000 },
    available: true,
  },
  {
    id: '93',
    name: 'Teachers Highland Cream',
    category: 'drinks',
    subcategory: 'whisky',
    price: 300,
    sizes: { '30ml': 170, '60ml': 320, '90ml': 470, '180ml': 900 },
    available: true,
  },
  {
    id: '94',
    name: 'Johnnie Walker Red Label',
    category: 'drinks',
    subcategory: 'whisky',
    price: 450,
    sizes: { '30ml': 250, '60ml': 450, '90ml': 650, '180ml': 1200 },
    available: true,
  },
  {
    id: '95',
    name: 'Johnnie Walker Black Label',
    category: 'drinks',
    subcategory: 'whisky',
    price: 650,
    sizes: { '30ml': 350, '60ml': 650, '90ml': 950, '180ml': 1800 },
    available: true,
  },
  {
    id: '96',
    name: "Jack Daniel's Old No.7",
    category: 'drinks',
    subcategory: 'whisky',
    price: 750,
    sizes: { '30ml': 400, '60ml': 750, '90ml': 1100, '180ml': 2100 },
    available: true,
  },
  // Rum
  {
    id: '97',
    name: 'Bacardi Superior Rum',
    category: 'drinks',
    subcategory: 'rum',
    price: 220,
    sizes: { '30ml': 120, '60ml': 220, '90ml': 320, '180ml': 600 },
    available: true,
  },
  {
    id: '98',
    name: 'Captain Morgan Spiced Rum',
    category: 'drinks',
    subcategory: 'rum',
    price: 220,
    sizes: { '30ml': 120, '60ml': 220, '90ml': 320, '180ml': 600 },
    available: true,
  },
  // Vodka
  {
    id: '99',
    name: 'Smirnoff Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 280,
    sizes: { '30ml': 150, '60ml': 280, '90ml': 410, '180ml': 780 },
    available: true,
  },
  {
    id: '100',
    name: 'Absolut Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 420,
    sizes: { '30ml': 220, '60ml': 420, '90ml': 620, '180ml': 1150 },
    available: true,
  },
  {
    id: '101',
    name: 'Grey Goose Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 850,
    sizes: { '30ml': 450, '60ml': 850, '90ml': 1250, '180ml': 2400 },
    available: true,
  },
  // Gin
  {
    id: '102',
    name: 'Beefeater Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 380,
    sizes: { '30ml': 200, '60ml': 380, '90ml': 560, '180ml': 1080 },
    available: true,
  },
  {
    id: '103',
    name: 'Tanqueray Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 460,
    sizes: { '30ml': 240, '60ml': 460, '90ml': 680, '180ml': 1300 },
    available: true,
  },
  {
    id: '104',
    name: "Hendrick's Gin",
    category: 'drinks',
    subcategory: 'gin',
    price: 720,
    sizes: { '30ml': 380, '60ml': 720, '90ml': 1060, '180ml': 2000 },
    available: true,
  },
  // Brandy
  {
    id: '105',
    name: 'Mansion House Brandy (Premium)',
    category: 'drinks',
    subcategory: 'brandy',
    price: 180,
    sizes: { '30ml': 80, '60ml': 150, '90ml': 220, '180ml': 420 },
    available: true,
  },
  {
    id: '106',
    name: 'Honey Bee Brandy (Premium)',
    category: 'drinks',
    subcategory: 'brandy',
    price: 170,
    sizes: { '30ml': 75, '60ml': 140, '90ml': 210, '180ml': 400 },
    available: true,
  },
  // Beer (additional)
  {
    id: '107',
    name: 'Heineken',
    category: 'drinks',
    subcategory: 'beer',
    price: 200,
    available: true,
  },
  {
    id: '108',
    name: 'Carlsberg',
    category: 'drinks',
    subcategory: 'beer',
    price: 190,
    available: true,
  },
  {
    id: '109',
    name: 'Tuborg Strong',
    category: 'drinks',
    subcategory: 'beer',
    price: 170,
    available: true,
  },
  {
    id: '110',
    name: 'Miller High Life',
    category: 'drinks',
    subcategory: 'beer',
    price: 210,
    available: true,
  },
  {
    id: '111',
    name: 'Stella Artois',
    category: 'drinks',
    subcategory: 'beer',
    price: 280,
    available: true,
  },
  // Whisky - additional Indian and imported
  {
    id: '112',
    name: 'Indri Single Malt',
    category: 'drinks',
    subcategory: 'whisky',
    price: 480,
    sizes: { '30ml': 260, '60ml': 480, '90ml': 700, '180ml': 1350 },
    available: true,
  },
  {
    id: '113',
    name: 'Paul John Brilliance',
    category: 'drinks',
    subcategory: 'whisky',
    price: 420,
    sizes: { '30ml': 230, '60ml': 420, '90ml': 620, '180ml': 1200 },
    available: true,
  },
  {
    id: '114',
    name: 'Glenfiddich 12YO',
    category: 'drinks',
    subcategory: 'whisky',
    price: 780,
    sizes: { '30ml': 420, '60ml': 780, '90ml': 1150, '180ml': 2200 },
    available: true,
  },
  {
    id: '115',
    name: 'Glenlivet 12YO',
    category: 'drinks',
    subcategory: 'whisky',
    price: 760,
    sizes: { '30ml': 410, '60ml': 760, '90ml': 1120, '180ml': 2150 },
    available: true,
  },
  {
    id: '116',
    name: 'Chivas Regal 12YO',
    category: 'drinks',
    subcategory: 'whisky',
    price: 700,
    sizes: { '30ml': 380, '60ml': 700, '90ml': 1020, '180ml': 1950 },
    available: true,
  },
  {
    id: '117',
    name: 'Jameson Irish Whiskey',
    category: 'drinks',
    subcategory: 'whisky',
    price: 520,
    sizes: { '30ml': 280, '60ml': 520, '90ml': 760, '180ml': 1450 },
    available: true,
  },
  {
    id: '118',
    name: 'Monkey Shoulder',
    category: 'drinks',
    subcategory: 'whisky',
    price: 680,
    sizes: { '30ml': 360, '60ml': 680, '90ml': 990, '180ml': 1900 },
    available: true,
  },
  // Rum - additional
  {
    id: '119',
    name: 'Old Monk Gold Reserve',
    category: 'drinks',
    subcategory: 'rum',
    price: 160,
    sizes: { '30ml': 75, '60ml': 140, '90ml': 200, '180ml': 380 },
    available: true,
  },
  {
    id: '120',
    name: 'Malibu Coconut Rum',
    category: 'drinks',
    subcategory: 'rum',
    price: 360,
    sizes: { '30ml': 190, '60ml': 360, '90ml': 520, '180ml': 980 },
    available: true,
  },
  {
    id: '121',
    name: 'Captain Morgan Dark Rum',
    category: 'drinks',
    subcategory: 'rum',
    price: 230,
    sizes: { '30ml': 120, '60ml': 230, '90ml': 340, '180ml': 640 },
    available: true,
  },
  // Vodka - additional
  {
    id: '122',
    name: 'Ketel One Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 520,
    sizes: { '30ml': 280, '60ml': 520, '90ml': 760, '180ml': 1450 },
    available: true,
  },
  {
    id: '123',
    name: 'Belvedere Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 900,
    sizes: { '30ml': 480, '60ml': 900, '90ml': 1320, '180ml': 2500 },
    available: true,
  },
  {
    id: '124',
    name: 'Skyy Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 350,
    sizes: { '30ml': 190, '60ml': 350, '90ml': 510, '180ml': 960 },
    available: true,
  },
  {
    id: '125',
    name: 'Cîroc Vodka',
    category: 'drinks',
    subcategory: 'vodka',
    price: 1000,
    sizes: { '30ml': 520, '60ml': 1000, '90ml': 1480, '180ml': 2800 },
    available: true,
  },
  // Gin - additional
  {
    id: '126',
    name: "Gordon's Gin",
    category: 'drinks',
    subcategory: 'gin',
    price: 320,
    sizes: { '30ml': 170, '60ml': 320, '90ml': 470, '180ml': 900 },
    available: true,
  },
  {
    id: '127',
    name: 'Roku Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 600,
    sizes: { '30ml': 320, '60ml': 600, '90ml': 880, '180ml': 1660 },
    available: true,
  },
  {
    id: '128',
    name: 'The Botanist Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 750,
    sizes: { '30ml': 400, '60ml': 750, '90ml': 1100, '180ml': 2100 },
    available: true,
  },
  {
    id: '129',
    name: 'Hapusa Himalayan Dry Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 520,
    sizes: { '30ml': 280, '60ml': 520, '90ml': 760, '180ml': 1450 },
    available: true,
  },
  {
    id: '130',
    name: 'Terai Indian Dry Gin',
    category: 'drinks',
    subcategory: 'gin',
    price: 480,
    sizes: { '30ml': 260, '60ml': 480, '90ml': 700, '180ml': 1350 },
    available: true,
  },
  // Brandy - additional
  {
    id: '131',
    name: 'Napoléon Brandy',
    category: 'drinks',
    subcategory: 'brandy',
    price: 220,
    sizes: { '30ml': 120, '60ml': 220, '90ml': 320, '180ml': 600 },
    available: true,
  },
  {
    id: '132',
    name: 'Hennessy VS (Cognac)',
    category: 'drinks',
    subcategory: 'cognac',
    price: 980,
    sizes: { '30ml': 520, '60ml': 980, '90ml': 1440, '180ml': 2800 },
    bottlePrice: 8500,
    available: true,
  },
  // Tequila
  {
    id: '151',
    name: 'Jose Cuervo Especial',
    category: 'drinks',
    subcategory: 'tequila',
    price: 420,
    sizes: { '30ml': 220, '60ml': 420, '90ml': 620 },
    bottlePrice: 3800,
    available: true,
  },
  {
    id: '152',
    name: 'Patrón Silver',
    category: 'drinks',
    subcategory: 'tequila',
    price: 900,
    sizes: { '30ml': 480, '60ml': 900, '90ml': 1320 },
    bottlePrice: 8200,
    available: true,
  },
  // Mezcal
  {
    id: '153',
    name: 'Montelobos Mezcal',
    category: 'drinks',
    subcategory: 'mezcal',
    price: 750,
    sizes: { '30ml': 400, '60ml': 750 },
    bottlePrice: 7000,
    available: true,
  },
  // Liqueurs
  {
    id: '154',
    name: 'Baileys Irish Cream',
    category: 'drinks',
    subcategory: 'liqueur',
    price: 360,
    sizes: { '30ml': 200 },
    glassPrice: 360,
    bottlePrice: 2500,
    available: true,
  },
  {
    id: '155',
    name: 'Kahlua Coffee Liqueur',
    category: 'drinks',
    subcategory: 'liqueur',
    price: 340,
    sizes: { '30ml': 190 },
    glassPrice: 340,
    bottlePrice: 2200,
    available: true,
  },
  {
    id: '156',
    name: 'Cointreau Orange Liqueur',
    category: 'drinks',
    subcategory: 'liqueur',
    price: 420,
    sizes: { '30ml': 220 },
    glassPrice: 420,
    bottlePrice: 3800,
    available: true,
  },
  // Shots
  {
    id: '157',
    name: 'Jägermeister Shot',
    category: 'drinks',
    subcategory: 'shots',
    price: 350,
    sizes: { '30ml': 350 },
    available: true,
  },
  {
    id: '158',
    name: 'Fireball Cinnamon Shot',
    category: 'drinks',
    subcategory: 'shots',
    price: 320,
    sizes: { '30ml': 320 },
    available: true,
  },
  // Cocktails (glass pricing)
  {
    id: '159',
    name: 'I Amsterdam Cocktail',
    category: 'drinks',
    subcategory: 'cocktail',
    price: 350,
    glassPrice: 350,
    available: true,
  },
  {
    id: '160',
    name: 'FML Cocktail',
    category: 'drinks',
    subcategory: 'cocktail',
    price: 380,
    glassPrice: 380,
    available: true,
  },
  // Mocktails
  {
    id: '161',
    name: 'Virgin Mojito',
    category: 'drinks',
    subcategory: 'mocktail',
    price: 220,
    glassPrice: 220,
    available: true,
  },
  {
    id: '162',
    name: 'Shirley Temple',
    category: 'drinks',
    subcategory: 'mocktail',
    price: 200,
    glassPrice: 200,
    available: true,
  },
  // Breezers
  {
    id: '163',
    name: 'Bacardi Breezer (Lime)',
    category: 'drinks',
    subcategory: 'breezers',
    price: 220,
    bottlePrice: 220,
    available: true,
  },
  {
    id: '164',
    name: 'Bacardi Breezer (Cranberry)',
    category: 'drinks',
    subcategory: 'breezers',
    price: 220,
    bottlePrice: 220,
    available: true,
  },
  // Shakes
  {
    id: '165',
    name: 'Chocolate Shake',
    category: 'drinks',
    subcategory: 'shakes',
    price: 180,
    glassPrice: 180,
    available: true,
  },
  {
    id: '166',
    name: 'Strawberry Shake',
    category: 'drinks',
    subcategory: 'shakes',
    price: 180,
    glassPrice: 180,
    available: true,
  },
  // Beer - craft and additional
  {
    id: '133',
    name: 'White Owl Spark',
    category: 'drinks',
    subcategory: 'beer',
    price: 220,
    available: true,
  },
  {
    id: '134',
    name: 'White Owl Diablo',
    category: 'drinks',
    subcategory: 'beer',
    price: 230,
    available: true,
  },
  {
    id: '135',
    name: 'Arbor Bangalore Bliss',
    category: 'drinks',
    subcategory: 'beer',
    price: 260,
    available: true,
  },
  // Wine - additional Indian labels (single price per glass/bottle representative)
  {
    id: '136',
    name: 'Sula Cabernet Shiraz',
    category: 'drinks',
    subcategory: 'wine',
    price: 320,
    available: true,
  },
  {
    id: '137',
    name: 'Sula Chenin Blanc',
    category: 'drinks',
    subcategory: 'wine',
    price: 300,
    available: true,
  },
  {
    id: '138',
    name: 'Grover La Réserve',
    category: 'drinks',
    subcategory: 'wine',
    price: 350,
    available: true,
  },
  {
    id: '139',
    name: 'Fratelli Sangiovese Bianco',
    category: 'drinks',
    subcategory: 'wine',
    price: 360,
    available: true,
  },
  // Additional Indian whisky mainstream under IMFL group
  {
    id: '140',
    name: 'Officer’s Choice Blue Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 150,
    sizes: { '30ml': 65, '60ml': 120, '90ml': 180, '180ml': 340 },
    available: true,
  },
  {
    id: '141',
    name: 'Signature Rare Aged Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 220,
    sizes: { '30ml': 110, '60ml': 210, '90ml': 310, '180ml': 600 },
    available: true,
  },
  {
    id: '142',
    name: 'Antiquity Blue Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 240,
    sizes: { '30ml': 120, '60ml': 230, '90ml': 340, '180ml': 650 },
    available: true,
  },
  {
    id: '143',
    name: 'Director’s Special Whisky',
    category: 'drinks',
    subcategory: 'imfl',
    price: 140,
    sizes: { '30ml': 60, '60ml': 110, '90ml': 165, '180ml': 300 },
    available: true,
  },
  {
    id: '144',
    name: 'Romanov Vodka',
    category: 'drinks',
    subcategory: 'imfl',
    price: 140,
    sizes: { '30ml': 65, '60ml': 120, '90ml': 180, '180ml': 340 },
    available: true,
  },
  {
    id: '145',
    name: 'Blue Riband Gin',
    category: 'drinks',
    subcategory: 'imfl',
    price: 160,
    sizes: { '30ml': 75, '60ml': 140, '90ml': 200, '180ml': 380 },
    available: true,
  },
  {
    id: '146',
    name: 'Contessa Rum',
    category: 'drinks',
    subcategory: 'imfl',
    price: 150,
    sizes: { '30ml': 70, '60ml': 130, '90ml': 190, '180ml': 360 },
    available: true,
  },
  {
    id: '147',
    name: 'Dependal XXX Rum',
    category: 'drinks',
    subcategory: 'imfl',
    price: 140,
    sizes: { '30ml': 65, '60ml': 120, '90ml': 180, '180ml': 340 },
    available: true,
  },
  {
    id: '148',
    name: 'Morena Rum',
    category: 'drinks',
    subcategory: 'imfl',
    price: 150,
    sizes: { '30ml': 70, '60ml': 130, '90ml': 190, '180ml': 360 },
    available: true,
  },
  {
    id: '149',
    name: 'MC Rum',
    category: 'drinks',
    subcategory: 'imfl',
    price: 140,
    sizes: { '30ml': 65, '60ml': 120, '90ml': 180, '180ml': 340 },
    available: true,
  },
  {
    id: '150',
    name: 'Old Adventurer Rum',
    category: 'drinks',
    subcategory: 'imfl',
    price: 150,
    sizes: { '30ml': 70, '60ml': 130, '90ml': 190, '180ml': 360 },
    available: true,
  },
];
